type: group
fields:
  color:
    type: colors
    label:
      en: Extracted Main Color
      de: Extrahierte Hauptfarbe
  focus:
    type: focus
    label:
      en: Focus Point
      de: Fokuspunkt
    help:
      en: Used for automatic cropping.
      de: Wird für das automatische Zuschneiden verwendet.