title: Default Page

tabs:
  # Content tab
  content:
    label:
      en: Content
      de: Inhalt
    columns:
      # Main content column
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              text:
                type: markdown
                size: huge

      # Sidebar column
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            label:
              en: Sub Pages
              de: Unterseiten
            template: default
          images:
            type: files
            label:
              en: Images
              de: Bilder
            template: image
            layout: cardlets
          files:
            type: files
            label:
              en: Files
              de: Dateien
            template: non-image

  # Metadata tab
  metadata: tabs/metadata

  # Info tab
  page-info: tabs/page-info
