#===============================================================================
# Site
#===============================================================================

title: Site

tabs:
  #Pages tab
  pages:
    label:
      en: Pages
      de: Seiten
    icon: list-bullet
    sections:
      pages:
        type: pages

  # Page tree tab
  pageTree:
    label:
      en: Page Tree
      de: Seitenbaum
    icon: folder-structure
    sections:
      info:
        type: fields
        fields:
          info:
            type: info
            label:
              en: Please note
              de: Bitte beachten
            text:
              en: "The page tree is for information only. You cannot move existing pages or add new pages here."
              de: "Der Seitenbaum dient nur zur Information. Sie können hier keine Seiten verschieben oder neue Seiten hinzufügen."
      pageTree:
        type: retrotree
        headline: Page Tree

  # Site Settings tab
  siteSettings:
    label:
      en: Site Settings
      de: Website-Einstellungen
    icon: settings
    sections:
      siteSettings:
        type: fields
        fields:
          siteLogo:
            type: files
            label:
              en: Site Logo
              de: Website-Logo
            width: 1/4
            uploads: site-logo
            required: true
            max: 1
            multiple: false
            layout: cards
          siteSocialShareImage:
            type: files
            label:
              en: Social Share Image
              de: Social-Share-Bild
            help:
              en: "Minimum dimensions: 1200 × 630 pixels. This image will be used as fallback if no specific image exists for a page."
              de: "Mindestmaße: 1200 × 630 Pixel. Dieses Bild wird als Fallback verwendet, wenn für eine Seite kein spezifisches Bild existiert."
            width: 1/4
            uploads: socialshare-image
            required: false
            max: 1
            multiple: false
            layout: cards
            image:
              ratio: 120/63
          defaultDivider:
            type: text
            required: true
            label:
              en: Default Divider Between the Elements in Metadata Titles
              de: Standard-Trennzeichen zwischen den Elementen in Metainfo-Titeln
            width: 1/4
            help:
              en: Typically one character like “–” or “|”
              de: Typischerweise ein Zeichen wie  „–“ oder „|“
            default: "|"
          twitterSiteHandle:
            type: text
            label:
              en: Twitter Handle of the Site
              de: Twitter-Account der Website
            help:
              en: Please include the leading “@” character
              de: Bitte mit dem „@“-Zeichen beginnen
            width: 1/4
            pattern: "^@([A-Za-z0-9_]{1,15})$"
          siteColorScheme:
            disabled: false
            type: structure
            label:
              en: Color Scheme
              de: Farbschema
            translate: false
            duplicate: false
            fields:
              id:
                type: slug
                label:
                  en: Unique ID
                  de: Eindeutige ID
                help:
                  en: "ATTENTION: This ID must be UNIQUE and must NEVER BE CHANGED once it has been set. Doing so would break the use of this color everywhere on the site."
                  de: "ACHTUNG: Diese ID muss EINDEUTIG sein und DARF NIEMALS GEÄNDERT werden, nachdem sie einmal gesetzt wurde. Andernfalls würde die Verwendung dieser Farbe auf der gesamten Website nicht mehr funktionieren."
                icon: key
                translate: false
                required: true
                width: 1/3
              name:
                type: text
                label:
                  en: Color Name
                  de: Farbname
                help:
                  en: "This name is used in option lists of select fields. So choose a meaningful and short name."
                  de: "Dieser Name wird in Optionslisten von Select-Feldern verwendet. Wählen Sie also einen aussagekräftigen und kurzen Namen."
                required: true
                width: 1/3
              includeInColorSelect:
                type: toggle
                label:
                  en: Include in Color Select Field
                  de: In Farbauswahlfeld aufnehmen
                help:
                  en: If enabled, website editors will see this color in color seleect fields.
                  de: Wenn aktiviert, sehen Website-Editoren diese Farbe in Farbauswahlfeldern.
                default: true
                width: 1/3
              lightMode:
                type: colors
                label:
                  en: Light Mode
                  de: Light Mode
                contrast: true
                default: "#ffffff"
                translate: false
                required: true
                width: 1/2
              darkMode:
                type: colors
                label:
                  en: Dark Mode
                  de: Dark Mode
                contrast: true
                default: "#000000"
                translate: false
                required: true
                width: 1/2
          siteColorSchemeWarning:
            type: info
            label:
              en: ATTENTION
              de: ACHTUNG
            text:
              en: Never delete a row in the color scheme table – unless you are absolutely sure what you are doing. Deleting colors may break the site.
              de: Löschen Sie niemals eine Zeile in der Farbschema-Tabelle – es sei denn, Sie wissen genau, was Sie tun. Das Löschen von Farben kann die fehlerfreie Darstellung der Website beeinträchtigen.
            theme: negative
      maintenanceMode: sections/maintenance

  # Uploaded files tab
  uploadedFiles: tabs/uploaded-files
