#===============================================================================
# Site
#===============================================================================

title: Site

tabs:
  pages:
    label:
      en: Pages
      de: Seiten
    icon: folder-structure
    sections:
      pages:
        type: pages

  siteSettings:
    label:
      en: Site Settings
      de: Website-Einstellungen
    icon: settings
    fields:
      siteLogo:
        type: files
        label:
          en: Site Logo
          de: Website-Logo
        width: 1/4
        query: site.images
        uploads: site-logo
        required: true
        max: 1
        multiple: false
        layout: cards
      defaultDivider:
        type: text
        required: true
        label:
          en: Default Divider Between the Elements in Metadata Titles
          de: Standard-Trennzeichen zwischen den Elementen in Metainfo-Titeln
        width: 1/2
        help:
          en: Typically one character like “–” or “|”
          de: Typischerweise ein Zeichen wie  „–“ oder „|“
        default: "|"
      twitterSiteHandle:
        type: text
        label:
          en: Twitter Handle of the Site
          de: Twitter-Account der Website
        help:
          en: Please include the leading “@” character
          de: Bitte mit dem „@“-Zeichen beginnen
        width: 1/4
        pattern: "^@([A-Za-z0-9_]{1,15})$"
